#!/usr/bin/zsh

unread() {
 notmuch new 2>&1 | grep -vE "\.(uidvalidity|mbsyncstate)$" && \
    printf 'Unread messages:\n' && \
    notmuch search tag:unread | awk '{print "  * " $0}'
}

if [ -z "$1" ]; then
    mbsync -a
elif [ -z "$2" ] && [ -f "~/mail/$1" ]; then
    mbsync "$1"
else
    mbsync "$@"
fi
[ $? -eq 0 ] && unread
