#!/usr/bin/zsh

unread() {
 notmuch new 2>&1 | grep -vE "\.(uidvalidity|mbsyncstate)$" && \
    printf 'Unread messages:\n' && \
    notmuch show --format=json --entire-thread=false "tag:unread" | ~/.mutt/scripts/nmpp
}

today() {
    notmuch show --format=json --entire-thread=false "date:today" | ~/.mutt/scripts/nmpp
}

if [ "$1" = "unread" ]; then
    unread && exit
elif [ "$1" = "today" ]; then
    today && exit
elif [ -z "$1" ]; then
    imapfilter
    parallel mbsync "{}" ::: $(ls ~/mail)
elif [ -z "$2" ] && [ -f "~/mail/$1" ]; then
    imapfilter
    mbsync "$1"
else
    imapfilter
    mbsync "$@"
fi
[ $? -eq 0 ] && unread
