#!/usr/bin/zsh

unread() {
 notmuch new 2>&1 | grep -vE "\.(uidvalidity|mbsyncstate)$" && \
    printf 'Unread messages:\n' && \
    notmuch show --format=json --entire-thread=false "tag:unread" | ~/.mutt/scripts/nmpp
}

if [ "$1" = "unread" ]; then
    unread && exit
elif [ -z "$1" ]; then
    mbsync -a
elif [ -z "$2" ] && [ -f "~/mail/$1" ]; then
    mbsync "$1"
else
    mbsync "$@"
fi
[ $? -eq 0 ] && unread
